version: '3'

services:
  db:
    image: mongodb
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
        MONGODB_HOST: mongo
        MONGODB_PORT: 27017
        MONGODB_USER: root
        MONGODB_PASSWORD: OTNmYTdjYmZkMjE5ZmYzODg0MDZiYWJh
        PYTHONPATH: /app


  app:
    build: .
    expose:
      - 8000
    ports:
      - 8000:8000
    environment:
        MONGODB_HOST: mongo
        MONGODB_PORT: 27017
        MONGODB_USER: root
        MONGODB_PASSWORD: OTNmYTdjYmZkMjE5ZmYzODg0MDZiYWJh
        PYTHONPATH: /app
    depends_on:
      - db
    volumes:
        - './:/app'
    restart: always